### ISSUE TITLE
cdk deploy bug!

### ISSUE THREAD

**Issue by notnonot** [aws-samples/aws-private-ca-matter-infrastructure#11]
The lib/index.js file uses aws javascript sdk v3, but that sdk can only be used for nodejs 18 runtime. And the nodejs 16 runtime used by the matterStacks.ts file, so cdk deploy --context generatePaa=1  command fails. Error: Cannot find module '@aws-sdk/client-acm-pca'.

Please fix it ASAP!!!

**Comment by hmphome** [comment]
Hello,

Thank you for reporting the issue.

We have tested with Node.js versions 16, 18, and 20, and cannot reproduce.

aws-sdk-js-v3 should work with earlier Node.js versions too, see https://github.com/aws/aws-sdk-js-v3#nodejs-versions

Please provide us with more detailed reproduction steps, e.g. download a clean copy of the repo, list versions of each tool being used, list all the commands being executed.

**Comment by notnonot** [comment]
But when I'm executing cdk deploy command according to the tutorial, I got an error, the error message is as follows:

MatterStackPAA: creating CloudFormation changeset...
3:02:07 PM | CREATE_FAILED        | Custom::ValidateVidType                     | ValidateVid
Received response status [FAILED] from custom resource. Message returned: Error: Cannot find module '@aws-sdk/client-acm-pca'
Require stack:
- /var/task/index.js
- /var/task/__entrypoint__.js
- /var/runtime/index.mjs
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
at Function.Module._load (node:internal/modules/cjs/loader:871:27)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object.<anonymous> (/var/task/index.js:1:63)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19) (RequestId: 03844885-24b4-4275-8921-abed0cd22f22)


 ❌  MatterStackPAA failed: Error: The stack named MatterStackPAA failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Cannot find module '@aws-sdk/client-acm-pca'
Require stack:
- /var/task/index.js
- /var/task/__entrypoint__.js
- /var/runtime/index.mjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/task/index.js:1:63)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19) (RequestId: 03844885-24b4-4275-8921-abed0cd22f22)
    at FullCloudFormationDeployment.monitorDeployment (/root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:400:135508

 ❌ Deployment failed: Error: The stack named MatterStackPAA failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Cannot find module '@aws-sdk/client-acm-pca'
Require stack:
- /var/task/index.js
- /var/task/__entrypoint__.js
- /var/runtime/index.mjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/task/index.js:1:63)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19) (RequestId: 03844885-24b4-4275-8921-abed0cd22f22)
    at FullCloudFormationDeployment.monitorDeployment (/root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /root/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:400:135508

The stack named MatterStackPAA failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: Cannot find module '@aws-sdk/client-acm-pca'
Require stack:
- /var/task/index.js
- /var/task/__entrypoint__.js
- /var/runtime/index.mjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/var/task/index.js:1:63)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19) (RequestId: 03844885-24b4-4275-8921-abed0cd22f22)

I also tried manually executing npm install @aws-sdk/client-acm-pca in the aws-private-ca-matter-infrastructure directory, but the result is still the same error.

**Comment by notnonot** [comment]
Nodejs version：nodejs 18
CDK version：2.81.0

**Comment by hmphome** [comment]
Thank you for additional information, that was really helpful!

Now I see what the issue is, however I still cannot reproduce it. Perhaps, they have updated Lambda in the PDX region and added the new AWS SDK.

Would you mind telling us what region you're trying it in?

As a workaround, you should be able to make it work by adding the `--no-rollback` switch to you `cdk deploy` command, then manually updating your `*MatterStackPAA-CustomLambdaFunctionUtilsCustomReso*` Lambda Function in AWS Console to use "Node.js 18.x", then running `cdk deploy` again.

There is no way to automate it from CDK script until CDK's CustomResource gets updated, I'll ping them. Or it should be possible to synthesize it into the CloudFormation template, then edit it to use "nodejs18.x" before deploying.

**Comment by notnonot** [comment]
The region I am using is the Tokyo region of Japan, I will try again following your suggestion. Thank you for your support.

**Comment by hmphome** [comment]
Fixed as the custom resource got updated and we could target Node.js 18.x.
